# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='award_achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('awarded_by', models.CharField(max_length=100)),
                ('awarded_at', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='award_fellowships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('awarded_by', models.CharField(max_length=100)),
                ('awarded_at', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('year_start', models.CharField(max_length=100)),
                ('year_end', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('office', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('residence', models.CharField(max_length=100)),
                ('about_me', models.CharField(max_length=2000)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.department')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('PI', models.CharField(max_length=100)),
                ('FA', models.CharField(max_length=100)),
                ('year_start', models.CharField(max_length=100)),
                ('year_end', models.CharField(max_length=100)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.professor')),
            ],
        ),
        migrations.CreateModel(
            name='publication_books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('published_at', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('co_authors', models.CharField(max_length=1000)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.professor')),
            ],
        ),
        migrations.CreateModel(
            name='publication_conferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('published_at', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('co_authors', models.CharField(max_length=1000)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.professor')),
            ],
        ),
        migrations.CreateModel(
            name='publication_journals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('published_at', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('co_authors', models.CharField(max_length=1000)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.professor')),
            ],
        ),
        migrations.CreateModel(
            name='publication_thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('published_at', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('co_authors', models.CharField(max_length=1000)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.professor')),
            ],
        ),
        migrations.CreateModel(
            name='student_completed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thesis_title', models.CharField(max_length=100)),
                ('year_start', models.CharField(max_length=100)),
                ('year_end', models.CharField(max_length=100)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.professor')),
            ],
        ),
        migrations.CreateModel(
            name='student_ongoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thesis_title', models.CharField(max_length=100)),
                ('year_start', models.CharField(max_length=100)),
                ('year_end', models.CharField(max_length=100)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.professor')),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.professor'),
        ),
        migrations.AddField(
            model_name='education',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.professor'),
        ),
        migrations.AddField(
            model_name='award_fellowships',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.professor'),
        ),
        migrations.AddField(
            model_name='award_achievement',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.professor'),
        ),
    ]
