# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='university',
            field=models.CharField(default='Indian Institute of Technology, Guwahati', max_length=100),
            preserve_default=False,
        ),
    ]
