# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0004_professor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='pic',
            field=models.FileField(default=set([0]), upload_to=b''),
            preserve_default=False,
        ),
    ]
