# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0006_auto_20171129_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='pic',
            field=models.ImageField(upload_to='profile_image'),
        ),
    ]
